version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region ap-south-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t codebuild-repo .
      - docker tag codebuild-repo:latest 466749146115.dkr.ecr.ap-south-1.amazonaws.com/codebuild-repo:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 466749146115.dkr.ecr.ap-south-1.amazonaws.com/codebuild-repo:latest
